---
title: "Análisis de Covid-19 en Costa Rica"
author: "Valery Murilo"
date: '2022-05-11'
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación 
Este documento presenta gráficos generados a partir de lo datos de covid-19  publicados por el Minsiterio de Salud [https://geovision.uned.ac.cr/oges/] (https://geovision.uned.ac.cr/oges/)
```{r carga-datos}
covid <- read.csv(file ="05_10_22_CSV_GENERAL.csv", sep=";")
```

## Entradas 

## Procesamiento

## Opciones generales 
### Curación de  Datos
```{r Conversión-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```
```{r opciones-generales}
options(scipen = 7)

```


## Salidas 

### Gráficos 

#### Casos acumuolados

##### Positivos
```{r casos-acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt= "n",
  yaxt= "n",
  main =  "casos acumulados positivos de COVID-19 en Costa Rica" ,
  xlab =  "fecha" ,
  ylab = "casos"
)
 ### Formato del eje X
axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%d/%m/%Y"),
  cex.axis = .7)



### Formato del eje X
axis(side = 2,
     covid$FECHA,
     labels = TRUE,
      at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)

```
#### Fallecidos 
```{r fallecidos-acumulados}
plot(
  covid$FECHA,
  covid$fallecidos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos fallecidos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos fallecidos"
)
# Formato del eje X
axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)
# Formato del eje Y
axis(
  side = 2,
  covid$fallecidos,
  labels = TRUE,  
  at = seq(0, 10000, by = 2000),
  cex.axis = .7
)

```

##### otros
```{r casos-otros-acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos",
  col = "blue"
)
# Casos activos
lines(covid$FECHA, covid$activos, col="red")
lines(covid$FECHA, covid$RECUPERADOS, col="green")
lines(covid$FECHA, covid$fallecidos, col="black")
      
# Leyenda
legend(
  x = "topleft",
  inset = 0.03,
  legend = c("Positivos", "Activos", "Recuperados", "Fallecidos"),
  col = c("blue", "red", "green", "black"),
  lty = 1,
  cex = 0.7)

# Formato del eje x
axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)
# Formato del eje y 
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)


```

```

